# Generated by Django 3.1.3 on 2020-11-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ta1', models.CharField(max_length=150)),
                ('Ta2', models.CharField(max_length=150, null=True)),
                ('Ta3', models.CharField(max_length=150, null=True)),
                ('Ta4', models.CharField(max_length=150, null=True)),
                ('C12Na', models.CharField(max_length=200, null=True)),
                ('C5Na', models.CharField(max_length=200, null=True)),
                ('NLSh', models.CharField(max_length=200, null=True)),
                ('C4Sh', models.CharField(max_length=200, null=True)),
                ('NSh', models.CharField(max_length=200, null=True)),
                ('NaF', models.CharField(max_length=200, null=True)),
                ('Na30F', models.CharField(max_length=200, null=True)),
                ('C12Sh', models.CharField(max_length=200, null=True)),
                ('B', models.CharField(max_length=200, null=True)),
                ('CTa', models.CharField(max_length=200, null=True)),
                ('CGI', models.CharField(max_length=200, null=True)),
                ('GI', models.CharField(max_length=200, null=True)),
                ('CSGI', models.CharField(max_length=200, null=True)),
                ('SGI', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
